config-version: 2
name: 'netsuite'
version: '0.5.0'
profile: 'integration'
require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  netsuite:
    +materialized: table
    +schema: netsuite
    netsuite:
      +enabled: "{{ var('data_model', 'netsuite2') == 'netsuite' }}" # doesn't work
      intermediate:
        +materialized: ephemeral

    netsuite2:
      +enabled: "{{ var('data_model', 'netsuite2') == 'netsuite2' }}" # it's just using the default value
      # intermediate:
      #   +materialized: ephemeral 

vars:
  netsuite:
    data_model: netsuite2

    accounting_books: "{{ ref('stg_netsuite__accounting_books') }}"
    accounting_periods: "{{ ref('stg_netsuite__accounting_periods') }}"
    accounts: "{{ ref('stg_netsuite__accounts') }}"
    classes: "{{ ref('stg_netsuite__classes') }}"
    consolidated_exchange_rates: "{{ ref('stg_netsuite__consolidated_exchange_rates') }}"
    currencies: "{{ ref('stg_netsuite__currencies') }}"
    customers: "{{ ref('stg_netsuite__customers') }}"
    departments: "{{ ref('stg_netsuite__departments') }}"
    expense_accounts: "{{ ref('stg_netsuite__expense_accounts') }}"
    income_accounts: "{{ ref('stg_netsuite__income_accounts') }}"
    items: "{{ ref('stg_netsuite__items') }}"
    locations: "{{ ref('stg_netsuite__locations') }}"
    subsidiaries: "{{ ref('stg_netsuite__subsidiaries') }}"
    transaction_lines: "{{ ref('stg_netsuite__transaction_lines') }}"
    transactions: "{{ ref('stg_netsuite__transactions') }}"
    vendor_types: "{{ ref('stg_netsuite__vendor_types') }}"
    vendors: "{{ ref('stg_netsuite__vendors') }}"
    accounting_book_subsidiaries: "{{ ref('stg_netsuite__accounting_book_subsidiaries') }}"
    accounting_period_fiscal_calendars: "{{ ref('stg_netsuite__accounting_period_fiscal_calendars') }}"
    account_types: "{{ ref('stg_netsuite__account_types') }}"
    entity_address: "{{ ref('stg_netsuite__entity_address') }}"
    location_main_address: "{{ ref('stg_netsuite__location_main_address') }}"
    vendor_categories: "{{ ref('stg_netsuite__vendor_categories') }}"
    jobs: "{{ ref('stg_netsuite__jobs') }}"
    entities: "{{ ref('stg_netsuite__entities') }}"
    transaction_accounting_lines: "{{ ref('stg_netsuite__transaction_accounting_lines') }}"

    accounts_pass_through_columns: []
    classes_pass_through_columns: []
    departments_pass_through_columns: []
    transactions_pass_through_columns: []
    transaction_lines_pass_through_columns: []
    balance_sheet_transaction_detail_columns: []
    income_statement_transaction_detail_columns: []

clean-targets:
- target
- dbt_modules
- dbt_packages
